### ISSUE TITLE
"Invalid literal for Fraction"

### ISSUE THREAD

**Issue by mid1221213** [jashandeep-sohi/webcam-filters#3]
On Ubuntu 21.04 (on which I had to install `python3-gst-1.0`):

```
$ webcam-filters --version
0.2.0
$ webcam-filters --input-dev /dev/video0 --output-dev /dev/video3 --background-blur 150
Traceback (most recent call last):
  File "/home/me/.local/bin/webcam-filters", line 8, in <module>
    sys.exit(cli())
  File "/home/me/.local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/me/.local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/me/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/me/.local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/me/.local/lib/python3.9/site-packages/webcam_filters/main.py", line 137, in cli
    add_filters(
  File "/home/me/.local/lib/python3.9/site-packages/webcam_filters/gst.py", line 87, in add_filters
    structs = sorted(
  File "/home/me/.local/lib/python3.9/site-packages/webcam_filters/gst.py", line 90, in <lambda>
    Fraction(str(x.get_value("framerate"))),
  File "/usr/lib/python3.9/fractions.py", line 115, in __new__
    raise ValueError('Invalid literal for Fraction: %r' %
ValueError: Invalid literal for Fraction: '{15/2,5/1}'
```

**Comment by jashandeep-sohi** [comment]
Looks like a bad assumption on my part when parsing device's framerate. Seems like they can be sets as well.

Can you post the output of `webcam-filters --list-dev-caps /dev/videoX`?

For me it looks like
```
         '/dev/video0' Capabilites          
┏━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┓
┃ Media Type  ┃ Width ┃ Height ┃ Framerate ┃
┡━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━┩
│ video/x-raw │ 1280  │ 720    │ 10/1      │
│ video/x-raw │ 960   │ 540    │ 15/1      │
│ video/x-raw │ 848   │ 480    │ 15/1      │
│ video/x-raw │ 640   │ 480    │ 30/1      │
│ video/x-raw │ 640   │ 360    │ 30/1      │
│ video/x-raw │ 424   │ 240    │ 30/1      │
│ video/x-raw │ 352   │ 288    │ 30/1      │
│ video/x-raw │ 320   │ 240    │ 30/1      │
│ video/x-raw │ 320   │ 180    │ 30/1      │
│ image/jpeg  │ 1280  │ 720    │ 30/1      │
│ image/jpeg  │ 960   │ 540    │ 30/1      │
│ image/jpeg  │ 848   │ 480    │ 30/1      │
│ image/jpeg  │ 640   │ 480    │ 30/1      │
│ image/jpeg  │ 640   │ 360    │ 30/1      │
│ image/jpeg  │ 424   │ 240    │ 30/1      │
│ image/jpeg  │ 352   │ 288    │ 30/1      │
│ image/jpeg  │ 320   │ 240    │ 30/1      │
│ image/jpeg  │ 320   │ 180    │ 30/1      │
└─────────────┴───────┴────────┴───────────┘

**Comment by bobek** [comment]
Facing the same issue, capabilities list for me looks like this

```
┏━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Media Type  ┃ Width ┃ Height ┃ Framerate                                ┃
┡━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ video/x-raw │ 2304  │ 1536   │ 2/1                                      │
│ video/x-raw │ 2304  │ 1296   │ 2/1                                      │
│ video/x-raw │ 1920  │ 1080   │ 5/1                                      │
│ video/x-raw │ 1600  │ 896    │ {15/2,5/1}                               │
│ video/x-raw │ 1280  │ 720    │ {10/1,15/2,5/1}                          │
│ video/x-raw │ 960   │ 720    │ {15/1,10/1,15/2,5/1}                     │
│ video/x-raw │ 1024  │ 576    │ {15/1,10/1,15/2,5/1}                     │
│ video/x-raw │ 800   │ 600    │ {24/1,20/1,15/1,10/1,15/2,5/1}           │
│ video/x-raw │ 864   │ 480    │ {24/1,20/1,15/1,10/1,15/2,5/1}           │
│ video/x-raw │ 800   │ 448    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ video/x-raw │ 640   │ 480    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ video/x-raw │ 640   │ 360    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ video/x-raw │ 432   │ 240    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ video/x-raw │ 352   │ 288    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ video/x-raw │ 320   │ 240    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ video/x-raw │ 320   │ 180    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ video/x-raw │ 176   │ 144    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ video/x-raw │ 160   │ 120    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ video/x-raw │ 160   │ 90     │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 1920  │ 1080   │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 1600  │ 896    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 1280  │ 720    │ {60/1,30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 960   │ 720    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 1024  │ 576    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 800   │ 600    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 864   │ 480    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 800   │ 448    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 640   │ 480    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 640   │ 360    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 432   │ 240    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 352   │ 288    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 320   │ 240    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 320   │ 180    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 176   │ 144    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 160   │ 120    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
│ image/jpeg  │ 160   │ 90     │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1}      │
└─────────────┴───────┴────────┴──────────────────────────────────────────┘
````

**Comment by jashandeep-sohi** [comment]
Oh my! So many options to choose from :)

Ok, I'll think of a patch for this.

In the mean time you should be able to side step the issue, by setting `--input-framerate` to one of the concrete framerates. @bobek  in your case that would only be `5/1` or `2/1` unfortunately.

**Comment by mid1221213** [comment]
In my case (Logitech C920 HD Pro), the capability list is:
```
$ webcam-filters --list-dev-caps /dev/video0
                      '/dev/video0' Capabilites                       
┏━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Media Type  ┃ Width ┃ Height ┃ Framerate                           ┃
┡━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ video/x-raw │ 2560  │ 1472   │ 2/1                                 │
│ video/x-raw │ 1920  │ 1080   │ 5/1                                 │
│ video/x-raw │ 1600  │ 896    │ {15/2,5/1}                          │
│ video/x-raw │ 1280  │ 720    │ {10/1,15/2,5/1}                     │
│ video/x-raw │ 960   │ 720    │ {15/1,10/1,15/2,5/1}                │
│ video/x-raw │ 1024  │ 576    │ {15/1,10/1,15/2,5/1}                │
│ video/x-raw │ 800   │ 600    │ {24/1,20/1,15/1,10/1,15/2,5/1}      │
│ video/x-raw │ 864   │ 480    │ {24/1,20/1,15/1,10/1,15/2,5/1}      │
│ video/x-raw │ 800   │ 448    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ video/x-raw │ 640   │ 480    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ video/x-raw │ 640   │ 360    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ video/x-raw │ 432   │ 240    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ video/x-raw │ 352   │ 288    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ video/x-raw │ 320   │ 240    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ video/x-raw │ 320   │ 180    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ video/x-raw │ 176   │ 144    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ video/x-raw │ 160   │ 120    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ video/x-raw │ 160   │ 90     │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 1920  │ 1080   │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 1600  │ 896    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 1280  │ 720    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 960   │ 720    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 1024  │ 576    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 800   │ 600    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 864   │ 480    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 800   │ 448    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 640   │ 480    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 640   │ 360    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 432   │ 240    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 352   │ 288    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 320   │ 240    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 320   │ 180    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 176   │ 144    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 160   │ 120    │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
│ image/jpeg  │ 160   │ 90     │ {30/1,24/1,20/1,15/1,10/1,15/2,5/1} │
└─────────────┴───────┴────────┴─────────────────────────────────────┘
```
and I tried the command line with adding `--input-framerate 2/1` or `--input-framerate 5/1` but no luck:
```
$ webcam-filters --input-dev /dev/video0 --output-dev /dev/video3 --background-blur 150 --input-framerate '5/1'
Traceback (most recent call last):
  File "/home/mid/.local/bin/webcam-filters", line 8, in <module>
    sys.exit(cli())
  File "/home/mid/.local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/mid/.local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/mid/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mid/.local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/mid/.local/lib/python3.9/site-packages/webcam_filters/main.py", line 137, in cli
    add_filters(
  File "/home/mid/.local/lib/python3.9/site-packages/webcam_filters/gst.py", line 152, in add_filters
    selfie.set_property("model", selfie_segmentation_model)
AttributeError: 'NoneType' object has no attribute 'set_property'
```
Am I missing something? Is it the same issue?
Thanks.

**Comment by bobek** [comment]
> Is it the same issue?

I was facing the same issue (I am on Debian), installed random additional gst packages, which solved the issue for me. (Sorry, I've installed bunch of them, not able at the moment to pinpoint which one really solved the problem for me)

**Comment by mid1221213** [comment]
> > Is it the same issue?
> 
> I was facing the same issue (I am on Debian), installed random additional gst packages, which solved the issue for me. (Sorry, I've installed bunch of them, not able at the moment to pinpoint which one really solved the problem for me)

Indeed. The missing package to install was `gstreamer1.0-python3-plugin-loader`, thanks!

Now it works, but I'm limited to 5 images per second, because of the Fraction issue.

**Comment by maximevince** [comment]
Just FYI, same issue here:

```
webcam-filters --list-dev-caps /dev/video0
                    '/dev/video0' Capabilites                    
┏━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Media Type  ┃ Width ┃ Height ┃ Framerate                      ┃
┡━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ video/x-raw │ 1280  │ 960    │ {15/2,5/1}                     │
│ video/x-raw │ 1280  │ 720    │ {15/2,5/1}                     │
│ video/x-raw │ 1184  │ 656    │ {10/1,5/1}                     │
│ video/x-raw │ 960   │ 720    │ {10/1,5/1}                     │
│ video/x-raw │ 1024  │ 576    │ {10/1,5/1}                     │
│ video/x-raw │ 960   │ 544    │ {15/1,10/1,5/1}                │
│ video/x-raw │ 800   │ 600    │ {20/1,15/1,10/1,5/1}           │
│ video/x-raw │ 864   │ 480    │ {20/1,15/1,10/1,5/1}           │
│ video/x-raw │ 800   │ 448    │ {20/1,15/1,10/1,5/1}           │
│ video/x-raw │ 752   │ 416    │ {25/1,20/1,15/1,10/1,5/1}      │
│ video/x-raw │ 640   │ 480    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ video/x-raw │ 640   │ 360    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ video/x-raw │ 544   │ 288    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ video/x-raw │ 432   │ 240    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ video/x-raw │ 352   │ 288    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ video/x-raw │ 320   │ 240    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ video/x-raw │ 320   │ 176    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ video/x-raw │ 176   │ 144    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ video/x-raw │ 160   │ 120    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 1280  │ 960    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 1280  │ 720    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 1184  │ 656    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 960   │ 720    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 1024  │ 576    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 960   │ 544    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 800   │ 600    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 864   │ 480    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 800   │ 448    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 752   │ 416    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 640   │ 480    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 640   │ 360    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 544   │ 288    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 432   │ 240    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 352   │ 288    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 320   │ 240    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 320   │ 176    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 176   │ 144    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
│ image/jpeg  │ 160   │ 120    │ {30/1,25/1,20/1,15/1,10/1,5/1} │
└─────────────┴───────┴────────┴────────────────────────────────┘
```

**Comment by jashandeep-sohi** [comment]
Ok, I think I've fixed this. Could you try `webcam-filters==0.2.1a0` and see if that helps?

**Comment by mid1221213** [comment]
> Ok, I think I've fixed this. Could you try `webcam-filters==0.2.1a0` and see if that helps?

It works better, thanks!
The only thing is that if one doesn't specify any constraint (like `--input-width`), the resolution / framerate chosen is not the best, and moreover the command exits immediately without error instead of staying running:
```
$ webcam-filters --input-dev /dev/video0 --output-dev /dev/video3 --background-blur 150
Selectd input: media-type=image/jpeg, width=1280 height=720 framerate=30/1

(python3:111307): GStreamer-CRITICAL **: 11:48:17.663: The created element should be floating, this is probably caused by faulty bindings

(python3:111307): GStreamer-CRITICAL **: 11:48:17.663: The created element should be floating, this is probably caused by faulty bindings

(python3:111307): GStreamer-CRITICAL **: 11:48:17.663: The created element should be floating, this is probably caused by faulty bindings
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
$ 
```
Here the best combination would have been 1920 × 1080 at 30FPS

**Comment by bobek** [comment]
> Ok, I think I've fixed this. Could you try `webcam-filters==0.2.1a0` and see if that helps?

It solves the fraction problem for me. Thank you!

```
~ ❯ webcam-filters --input-dev /dev/video4 --output-dev /dev/video6 --background-blur 30
Selectd input: media-type=image/jpeg, width=1280 height=720 framerate=30/1
```

**Comment by jashandeep-sohi** [comment]
> > Ok, I think I've fixed this. Could you try `webcam-filters==0.2.1a0` and see if that helps?
> 
> It works better, thanks!
> The only thing is that if one doesn't specify any constraint (like `--input-width`), the resolution / framerate chosen is not the best, and moreover the command exits immediately without error instead of staying running:
> 
> ```
> $ webcam-filters --input-dev /dev/video0 --output-dev /dev/video3 --background-blur 150
> Selectd input: media-type=image/jpeg, width=1280 height=720 framerate=30/1
> 
> (python3:111307): GStreamer-CRITICAL **: 11:48:17.663: The created element should be floating, this is probably caused by faulty bindings
> 
> (python3:111307): GStreamer-CRITICAL **: 11:48:17.663: The created element should be floating, this is probably caused by faulty bindings
> 
> (python3:111307): GStreamer-CRITICAL **: 11:48:17.663: The created element should be floating, this is probably caused by faulty bindings
> INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
> $ 
> ```
> 
> Here the best combination would have been 1920 × 1080 at 30FPS

Yes, this was conscious change. I'm picking the input that's _closest_ to `--input{width, height, framerate}` rather than exactly that. Picking the "best" (i.e. the highest framerate, width, height) might not give you the best experience. For example, I doubt you could push 60fps through this without getting some serious frame drops. So the defaults for `--input{width, height, framerate}` are a "reasonable" 720p at 30fps and we select a input that's closest to that.

If you'd like to default to 1080p at 30fps (or something else more optimal), I'd just create an alias:

```
alias webcam-filters='webcam-filters --input-width 1920 --input-height 1080 --input-framerate 30'
```

**Comment by mid1221213** [comment]
> > > Ok, I think I've fixed this. Could you try `webcam-filters==0.2.1a0` and see if that helps?
> > 
> > It works better, thanks!
> > The only thing is that if one doesn't specify any constraint (like `--input-width`), the resolution / framerate chosen is not the best, and moreover the command exits immediately without error instead of staying running:
> > ```
> 
> Yes, this was conscious change. I'm picking the input that's _closest_ to `--input{width, height, framerate}` rather than exactly that. Picking the "best" (i.e. the highest framerate, width, height) might not give you the best experience. For example, I doubt you could push 60fps through this without getting some serious frame drops. So the defaults for `--input{width, height, framerate}` are a "reasonable" 720p at 30fps and we select a input that's closest to that.
> 
> If you'd like to default to 1080p at 30fps (or something else more optimal), I'd just create an alias:
> 
> ```
> alias webcam-filters='webcam-filters --input-width 1920 --input-height 1080 --input-framerate 30'
> ```

Ok, I wasn't aware it was on purpose, so no problem. Thanks for the explanation.

But there is still the other problem that makes it exit instantly after launch if I don't specify any size / framerate constraint. There isn't any error message, the return code is `0`, the light on my webcam is lit for an instant, then everything stops and I get the shell prompt. Do you want me to open another issue for this?

**Comment by jashandeep-sohi** [comment]
Interesting, yes please. Sorry, I misunderstood that was also an issue. Closing this one.
