### ISSUE TITLE
Caps object is not iterable

### ISSUE THREAD

**Issue by jekkos** [jashandeep-sohi/webcam-filters#34]
When running webcam-filters I get the following traceback

```
➜  ~ webcam-filters --verbose --input-dev /dev/video0 --output-dev /dev/video3 --background-blur 150

Traceback (most recent call last):
  File "/home/restore/.local/bin/webcam-filters", line 9, in <module>
    sys.exit(main())
  File "/home/restore/.local/lib/python3.8/site-packages/webcam_filters/__main__.py", line 5, in main
    cli.main(prog_name="webcam-filters")
  File "/home/restore/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/restore/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/restore/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/restore/.local/lib/python3.8/site-packages/webcam_filters/main.py", line 154, in cli
    add_filters(
  File "/home/restore/.local/lib/python3.8/site-packages/webcam_filters/gst.py", line 98, in add_filters
    for s in caps:
TypeError: 'Caps' object is not iterable

```

I tried different devices but always the same result. Anything else I can check?

**Comment by hs-neax** [comment]
I'm having the same issue on an up-to-date arch:
_gst-python 1.18.5-1
gstreamer 1.18.5-1
Python 3.9.7_

**Comment by jekkos** [comment]
Ok the error went away after running

```
sudo apt install python3-gst-1.0
```
can be closed, thx

**Comment by jekkos** [comment]
Wait, now I'm seeing this error

```
Error from /GstPipeline:pipeline0/GstV4l2Sink:v4l2sink0: Could not open device '/dev/video2' for reading and writing.
```

my video2 device is a virtual one created by v4l2 loopback. Any idea why this is?

**Comment by jashandeep-sohi** [comment]
> Wait, now I'm seeing this error
> 
> ```
> Error from /GstPipeline:pipeline0/GstV4l2Sink:v4l2sink0: Could not open device '/dev/video2' for reading and writing.
> ```
> 
> my video2 device is a virtual one created by v4l2 loopback. Any idea why this is?

What are the kernel mod parameters you created this device with?

To rule out if this is a problem with `webcam-filters` can you run the following basic gstreamer pipeline:

```
gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! video/x-raw, format=YUY2 ! v4l2sink device=/dev/video2
```

**Comment by jashandeep-sohi** [comment]
> I'm having the same issue on an up-to-date arch: _gst-python 1.18.5-1 gstreamer 1.18.5-1 Python 3.9.7_

Is `gst-plugins-base` and `gst-plugins-good` also installed?

**Comment by hs-neax** [comment]
@jashandeep-sohi: Yes they are. Don't know whats causing it. I created a Dockerfile instead, since I considered that more useful as an alternative to nix than fixing user system specific stuff. Maybe it'd be worth adding that to the repo in a bit more generalized start.sh.

**Dockerfile**
```
FROM ubuntu:impish

ENV DEBIAN_FRONTEND="noninteractive" 
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3.9 \
    python3-pip \
    python3-gi python3-gi-cairo gir1.2-gtk-3.0 \
    gstreamer1.0-plugins-good gstreamer1.0-plugins-base-apps gstreamer1.0-x python3-gst-1.0 gstreamer1.0-python3-plugin-loader

RUN pip install --pre webcam-filters

COPY start.sh .

CMD ["/bin/bash","start.sh"]
```
**start.sh**
```
#!/bin/bash

webcam-filters --input-dev /dev/video0 --output-dev /dev/video10 --background-blur 150
```
`$ docker run  --device=/dev/video0:/dev/video0 --device=/dev/video10:/dev/video10  webcam-filters`

**Comment by DmitrySandalov** [comment]
Please add Ubuntu installation instructions to README.md

**Comment by jashandeep-sohi** [comment]
Apologies for the delayed response.

@hs-neax  Happy to discuss any contributions in a PR. My reasoning for using Nix vs Docker was to have as "native" an experience as possible without having to mount any devices into a container run by the docker daemon (as root). It's been flaky for me in the past.

I don't mind adding a Dockerfile if that makes life easier, but I'm not sure I want to maintain a parallel file with dependencies for installing this. If possible, I'd prefer it if the Dockerfile also installed it using Nix or the container was built using Nix. And then CI can just push the image out to a public repository.

@DmitrySandalov Sounds good! I did pin #11, but it's probably a good idea to add that to the README.

**Comment by hs-neax** [comment]
@jashandeep-sohi: Sorry for the big delay. I understand your point about maintenance and made PR with a simple Docker container wrapping a Nix installation. I'm using it for a while now and it's working well.

**Comment by sboehringer** [comment]
I get the same error on openSUSE Tumbleweed 20221124. All dependencies seem to be installed.
