### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'set_property'" when setting blur

### ISSUE THREAD

**Issue by kelnos** [jashandeep-sohi/webcam-filters#4]
Running Debian bullseye here, with python 3.9 and gstreamer 1.18.4 (though python3-gst 1.18.3).  When I try to start things up (after creating a v4l2loopback device per the README, at /dev/video11):
```
$ webcam-filters --input-dev /dev/video2 --output-dev /dev/video11 --background-blur 150
Traceback (most recent call last):
  File "/home/brian/.local/bin/webcam-filters", line 8, in <module>
    sys.exit(cli())
  File "/home/brian/.local/pipx/venvs/webcam-filters/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/brian/.local/pipx/venvs/webcam-filters/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/brian/.local/pipx/venvs/webcam-filters/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brian/.local/pipx/venvs/webcam-filters/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/brian/.local/pipx/venvs/webcam-filters/lib/python3.9/site-packages/webcam_filters/main.py", line 137, in cli
    add_filters(
  File "/home/brian/.local/pipx/venvs/webcam-filters/lib/python3.9/site-packages/webcam_filters/gst.py", line 152, in add_filters
    selfie.set_property("model", selfie_segmentation_model)
AttributeError: 'NoneType' object has no attribute 'set_property'
```

**Comment by callum-ryan** [comment]
I had this error on Arch - installing `gst-plugins-good` fixed the problem.

**Comment by kelnos** [comment]
> I had this error on Arch - installing `gst-plugins-good` fixed the problem.

I do have it installed already.  Any idea what specific plugin it needs from that package?  Maybe it's in a different plugins package on Debian...

**Comment by callum-ryan** [comment]
> I do have it installed already. Any idea what specific plugin it needs from that package? Maybe it's in a different plugins package on Debian...

I have just realised that I was getting the same error message but at a different part of the code. For me I needed `v4l2src` which is in the good plugins. Apologies.

**Comment by kelnos** [comment]
Ah, gotcha.  From what I can tell, I do have that... at least, `gst-inspect-1.0 v4l2src` does return information as I'd expect.

**Comment by jashandeep-sohi** [comment]
Someone else mentioned in https://github.com/jashandeep-sohi/webcam-filters/issues/3#issuecomment-909224085 they needed `gstreamer1.0-python3-plugin-loader`. I believe it provides `lib/gstreamer-1.0/libgstpython.so`, which on Arch is just bundled in https://archlinux.org/packages/extra/x86_64/gst-python/. 

And yes, `gst-plugins-good ` is also needed. I forgot to mention that in  the README.

**Comment by kelnos** [comment]
Installing the plugin loader package did it.  Thanks for your help!

**Comment by hsanjuan** [comment]
I have the same problem on OpenSUSE, and `/usr/lib64/gstreamer-1.0/libgstpython.so` and gst-plugins-good are there (gst-inspect-1.0 v4l2src` works). Any other ideas? Things work without blur.

**Comment by jashandeep-sohi** [comment]
@hsanjuan can you post the output of `GST_DEBUG=GST_PLUGIN_LOADING:4,pyplugin:6 webcam-filters --background-blur 50 ...`

**Comment by hsanjuan** [comment]
```
[23:21:59] ~ $ GST_DEBUG=GST_PLUGIN_LOADING:4,pyplugin:6 webcam-filters --background-blur 50 --input-dev /dev/video5 --output-dev /dev/video0
0:00:00.000268384 18134 0x5626dde96a70 INFO      GST_PLUGIN_LOADING gstplugin.c:325:_priv_gst_plugin_initialize: registering 0 static plugins
0:00:00.000325815 18134 0x5626dde96a70 INFO      GST_PLUGIN_LOADING gstplugin.c:233:gst_plugin_register_static: registered static plugin "staticelements"
0:00:00.000332994 18134 0x5626dde96a70 INFO      GST_PLUGIN_LOADING gstplugin.c:235:gst_plugin_register_static: added static plugin "staticelements", result: 1
0:00:00.197454235 18134 0x5626dde96a70 INFO      GST_PLUGIN_LOADING gstplugin.c:915:_priv_gst_plugin_load_file_for_registry: plugin "/usr/lib64/gstreamer-1.0/libgstvideo4linux2.so" loaded
Selectd input: media-type=image/jpeg, width=1280 height=720 framerate=30/1
0:00:00.210186485 18134 0x5626dde96a70 INFO      GST_PLUGIN_LOADING gstplugin.c:915:_priv_gst_plugin_load_file_for_registry: plugin "/usr/lib64/gstreamer-1.0/libgstcoreelements.so" loaded
0:00:00.215944899 18134 0x5626dde96a70 INFO      GST_PLUGIN_LOADING gstplugin.c:915:_priv_gst_plugin_load_file_for_registry: plugin "/usr/lib64/gstreamer-1.0/libgstplayback.so" loaded
0:00:00.218019679 18134 0x5626dde96a70 INFO      GST_PLUGIN_LOADING gstplugin.c:915:_priv_gst_plugin_load_file_for_registry: plugin "/usr/lib64/gstreamer-1.0/libgstvideoconvert.so" loaded
Traceback (most recent call last):
  File "/home/hector/.local/bin/webcam-filters", line 8, in <module>
    sys.exit(cli())
  File "/home/hector/.local/pipx/venvs/webcam-filters/lib64/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/hector/.local/pipx/venvs/webcam-filters/lib64/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/hector/.local/pipx/venvs/webcam-filters/lib64/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hector/.local/pipx/venvs/webcam-filters/lib64/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/hector/.local/pipx/venvs/webcam-filters/lib64/python3.9/site-packages/webcam_filters/main.py", line 139, in cli
    add_filters(
  File "/home/hector/.local/pipx/venvs/webcam-filters/lib64/python3.9/site-packages/webcam_filters/gst.py", line 159, in add_filters
    selfie.set_property("model", selfie_segmentation_model)
AttributeError: 'NoneType' object has no attribute 'set_property'
```
