### ISSUE TITLE
Error while running the demo commands

### ISSUE THREAD

**Issue by vincit-haihala** [jashandeep-sohi/webcam-filters#5]
`$ webcam-filters --input-dev /dev/video0 --output-dev /dev/video3 --background-blur 150`

```
Traceback (most recent call last):
  File "/home/eeroh/.local/bin/webcam-filters", line 8, in <module>
    sys.exit(cli())
  File "/home/eeroh/.local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/eeroh/.local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/eeroh/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/eeroh/.local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/eeroh/.local/lib/python3.9/site-packages/webcam_filters/main.py", line 137, in cli
    add_filters(
  File "/home/eeroh/.local/lib/python3.9/site-packages/webcam_filters/gst.py", line 68, in add_filters
    for c in caps:
TypeError: 'Caps' object is not iterable
```

**Comment by topazas** [comment]
same here, ubuntu 21, python 3.9

**Comment by jgrgt** [comment]
I got past that after installing `python3-gst-1.0`. Now I get:

```
Traceback (most recent call last):
  File "/home/jgrgt/.local/bin/webcam-filters", line 8, in <module>
    sys.exit(cli())
  File "/home/jgrgt/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/jgrgt/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/jgrgt/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jgrgt/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/jgrgt/.local/lib/python3.8/site-packages/webcam_filters/main.py", line 137, in cli
    add_filters(
  File "/home/jgrgt/.local/lib/python3.8/site-packages/webcam_filters/gst.py", line 87, in add_filters
    structs = sorted(
  File "/home/jgrgt/.local/lib/python3.8/site-packages/webcam_filters/gst.py", line 90, in <lambda>
    Fraction(str(x.get_value("framerate"))),
  File "/usr/lib/python3.8/fractions.py", line 137, in __new__
    raise ValueError('Invalid literal for Fraction: %r' %
ValueError: Invalid literal for Fraction: '{5/1,5/1}'
```

**Comment by steveharriss** [comment]
Exactly the same errors on 5.13.12-artix1-1. Python 3.9.6. Initially got the `'TypeError: 'Caps' object is not iterable'`.

Then installed gst-python-1.18.4-1-x86_64 and get the `'Invalid literal for Fraction:'` error.

Only difference being: 
```
File "/usr/lib/python3.9/fractions.py", line 115, in __new__
    raise ValueError('Invalid literal for Fraction: %r' %
ValueError: Invalid literal for Fraction: '{30/1,15/1}'
```

**Comment by jgrgt** [comment]
There's a workaround for the fraction issue in #3

**Comment by jashandeep-sohi** [comment]
Closing. The fraction bug is fixed and if you're still having problems with dependencies, try installing with Nix:

`nix-env --file https://github.com/jashandeep-sohi/webcam-filters/archive/refs/tags/v0.2.2.tar.gz --install`
