### ISSUE TITLE
Caps is not iterable

### ISSUE THREAD

**Issue by raffaem** [jashandeep-sohi/webcam-filters#92]
I'm on master

```
❯ webcam-filters --input-dev /dev/video0 --output-dev /dev/vid
eo3 --background-blur 150
Traceback (most recent call last):
  File "/home/raffaele/.local/bin/webcam-filters", line 8, in <module>
    sys.exit(main())
  File "/home/raffaele/.local/lib/python3.10/site-packages/webcam_filters/__main__.py", line 5, in main
    cli.main(prog_name="webcam-filters")
  File "/home/raffaele/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/raffaele/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/raffaele/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/raffaele/.local/lib/python3.10/site-packages/webcam_filters/main.py", line 156, in cli
    p.run()
  File "/home/raffaele/.local/lib/python3.10/site-packages/webcam_filters/gst.py", line 114, in run
    pipeline = self.build_pipeline()
  File "/home/raffaele/.local/lib/python3.10/site-packages/webcam_filters/gst.py", line 186, in build_pipeline
    input_caps = self.select_input()
  File "/home/raffaele/.local/lib/python3.10/site-packages/webcam_filters/gst.py", line 150, in select_input
    for s in caps:
TypeError: 'Caps' object is not iterable
```

**Comment by jashandeep-sohi** [comment]
Most likely your distro has a old version of gstreamer or the gstreamer Python bindings. Try running it with Nix or Docker to rule that out.

```
docker run -it \
  --device=/dev/video0:/input-dev \
  --device=/dev/video3:/output-dev \
  ghcr.io/jashandeep-sohi/webcam-filters:master --background-blur 50
```

**Comment by raffaem** [comment]
The docker version works after I have created the output virtual camera manually with v4l2loopback options.

> Most likely your distro has a old version of gstreamer or the gstreamer Python bindings. 

I don't understand how that would be possible.

I have Arch which is a rolling release, so gstreamer should be fine.
I have pip-installed the software, so also the requirements, a few days ago, so also the Python bindings should be fine.

**Comment by jashandeep-sohi** [comment]
Interesting, I'm on Arch as well but it's working for me. I just tried installing it from master. Here's what pacman reports:
```
$ pacman -Q | grep gst
clutter-gst 3.0.27-4
gst-plugin-pipewire 1:0.3.59-3
gst-plugins-bad 1.20.4-1
gst-plugins-bad-libs 1.20.4-1
gst-plugins-base 1.20.4-1
gst-plugins-base-libs 1.20.4-1
gst-plugins-good 1.20.4-1
gst-python 1.20.4-1
gstreamer 1.20.4-1
gstreamer-vaapi 1.20.4-1
```

**Comment by raffaem** [comment]
Here it is for me:

```
❯ pacman -Q | grep gst
clutter-gst 3.0.27-4
gst-editing-services 1.20.4-3
gst-libav 1.20.4-3
gst-plugin-gtk 1.20.4-3
gst-plugins-bad 1.20.4-3
gst-plugins-bad-libs 1.20.4-3
gst-plugins-base 1.20.4-3
gst-plugins-base-libs 1.20.4-3
gst-plugins-good 1.20.4-3
gstreamer 1.20.4-3
phonon-qt5-gstreamer 4.10.0-3
```

bah, maybe I did something wrong in installing it. Thanks.
